# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  name: Default
  vmImage: ubuntu-latest

steps:
  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis configuration'
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'petretiandrea-1'
      scannerMode: 'CLI'
      configMode: 'manual'
      cliProjectKey: 'petretiandrea_spring-boot3'
      cliProjectName: 'spring-boot3'
      cliSources: './src'
      extraProperties: |
        sonar.javascript.lcov.reportPaths=./coverage/lcov.info
        sonar.clover.reportPath=./coverage/clover.xml
        sonar.typescript.tsconfigPaths=tsconfig.json,tsconfig.build.json
        sonar.test.inclusions=**/__tests__/*, **/*.spec.ts
        sonar.coverage.exclusions=src/main.ts,src/app.module.ts,src/statisticsMonitor.ts,src/publisher/logPublisher.ts,src/config/*.ts,test/integrationUtils.ts


  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '18.16.1'
  - script: npm install --global yarn
    displayName: "Install Yarn"
  
  - script: |
      yarn install
      yarn run test:ci:cov
    displayName: "Run tests and collecting coverage"
    
  - task: SonarCloudAnalyze@1
    inputs:
      jdkversion: 'JAVA_HOME_11_X64'
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'