source:
  type: "cdc"
  config:
    uri: ${MONGO_DB_URI}
    dbName: ${MONGO_DB_NAME:rtd}
    collectionName: ${OUTBOX_COLLECTION_NAME:test}
    aggregationPipeline:
      [
        { $match: { operationType: { $in: ["insert", "update", "replace"] } } },
        { $project: { _id: 1, fullDocument: 1, ns: 1, documentKey: 1 } },
      ]
    checkpoint:
      uri: ${OUTBOX_CHECKPOINT_MONGODB_URI}
      checkpointEvery: ${CHECKPOINT_EVERY}

publisher:
  type: kafka
  topic: ${OUTBOX_KAFKA_TOPIC:events}
  config:
    broker: ${OUTBOX_KAFKA_BROKER:localhost:29095}
    sasl_jaas: ${OUTBOX_KAFKA_SASL_JAAS}


pipeline:
  type: "full"